import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/organisms/Navbar";
import styles from './page.module.scss'
import { CartSidebarProvider } from "@/context/cartSidebar";
import CartSidebar from "@/components/organisms/CartSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartSidebarProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className={styles.header}>
            <Navbar />
            <CartSidebar />
          </header>

          <main className="container">
            {children}
          </main>
        </body>
      </html>
    </CartSidebarProvider>
  );
}
